networks:
  qdrant_net:
    driver: overlay
    attachable: true

services:
  qdrant_node_0:
    image: y0mg/qdrant-raspberry-pi
    entrypoint: ["/bin/bash", "-c"]
    command: ["sleep 10 && exec qdrant --uri http://qdrant_node_0:6335"]
    restart: always
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__P2P__PORT=6335
      - QDRANT__CLUSTER__CONSENSUS__MAX_MESSAGE_QUEUE_SIZE=5000
      - QDRANT__CLUSTER__CONSENSUS__TICK_PERIOD_MS=100
      - QDRANT__CLUSTER__CONSENSUS__BOOTSTRAP_TIMEOUT_SEC=30
      - QDRANT__STORAGE__SNAPSHOT_PATH=/qdrant/snapshots
      - QDRANT__LOG_LEVEL=debug,raft=debug
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - qdrant_net
    volumes:
      - qdrant_data_0:/qdrant/storage
      - qdrant_snapshots_0:/qdrant/snapshots
    deploy:
      resources:
        limits:
          cpus: '1'

  qdrant_node_1:
    image: y0mg/qdrant-raspberry-pi
    entrypoint: ["/bin/sh", "-c"]
    command: ["sleep 20 && exec qdrant --bootstrap http://qdrant_node_0:6335 --uri http://qdrant_node_1:6335"]
    restart: always
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__P2P__PORT=6335
      - QDRANT__CLUSTER__CONSENSUS__MAX_MESSAGE_QUEUE_SIZE=5000
      - QDRANT__CLUSTER__CONSENSUS__TICK_PERIOD_MS=100
      - QDRANT__CLUSTER__CONSENSUS__BOOTSTRAP_TIMEOUT_SEC=30
      - QDRANT__STORAGE__SNAPSHOT_PATH=/qdrant/snapshots
      - QDRANT__LOG_LEVEL=debug,raft=debug
    ports:
      - "6343:6333"
      - "6344:6334"
    networks:
      - qdrant_net
    volumes:
      - qdrant_data_1:/qdrant/storage
      - qdrant_snapshots_1:/qdrant/snapshots
    deploy:
      resources:
        limits:
          cpus: '1'

  qdrant_node_2:
    image: y0mg/qdrant-raspberry-pi
    entrypoint: ["/bin/sh", "-c"]
    command: ["sleep 30 && exec qdrant --bootstrap http://qdrant_node_0:6335 --uri http://qdrant_node_2:6335"]
    restart: always
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__P2P__PORT=6335
      - QDRANT__CLUSTER__CONSENSUS__MAX_MESSAGE_QUEUE_SIZE=5000
      - QDRANT__CLUSTER__CONSENSUS__TICK_PERIOD_MS=100
      - QDRANT__CLUSTER__CONSENSUS__BOOTSTRAP_TIMEOUT_SEC=30
      - QDRANT__STORAGE__SNAPSHOT_PATH=/qdrant/snapshots
      - QDRANT__LOG_LEVEL=debug,raft=debug
    ports:
      - "6353:6333"
      - "6354:6334"
    networks:
      - qdrant_net
    volumes:
      - qdrant_data_2:/qdrant/storage
      - qdrant_snapshots_2:/qdrant/snapshots
    deploy:
      resources:
        limits:
          cpus: '1'

  qdrant_node_3:
    image: y0mg/qdrant-raspberry-pi
    entrypoint: ["/bin/sh", "-c"]
    command: ["sleep 40 && exec qdrant --bootstrap http://qdrant_node_0:6335 --uri http://qdrant_node_3:6335"]
    restart: always
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__P2P__PORT=6335
      - QDRANT__CLUSTER__CONSENSUS__MAX_MESSAGE_QUEUE_SIZE=5000
      - QDRANT__CLUSTER__CONSENSUS__TICK_PERIOD_MS=100
      - QDRANT__CLUSTER__CONSENSUS__BOOTSTRAP_TIMEOUT_SEC=30
      - QDRANT__STORAGE__SNAPSHOT_PATH=/qdrant/snapshots
      - QDRANT__LOG_LEVEL=debug,raft=debug
    ports:
      - "6363:6333"
      - "6364:6334"
    networks:
      - qdrant_net
    volumes:
      - qdrant_data_3:/qdrant/storage
      - qdrant_snapshots_3:/qdrant/snapshots
    deploy:
      resources:
        limits:
          cpus: '1'

  qdrant_node_4:
    image: y0mg/qdrant-raspberry-pi
    entrypoint: ["/bin/sh", "-c"]
    command: ["sleep 50 && exec qdrant --bootstrap http://qdrant_node_0:6335 --uri http://qdrant_node_4:6335"]
    restart: always
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__P2P__PORT=6335
      - QDRANT__CLUSTER__CONSENSUS__MAX_MESSAGE_QUEUE_SIZE=5000
      - QDRANT__CLUSTER__CONSENSUS__TICK_PERIOD_MS=100
      - QDRANT__CLUSTER__CONSENSUS__BOOTSTRAP_TIMEOUT_SEC=30
      - QDRANT__STORAGE__SNAPSHOT_PATH=/qdrant/snapshots
      - QDRANT__LOG_LEVEL=debug,raft=debug
    ports:
      - "6373:6333"
      - "6374:6334"
    networks:
      - qdrant_net
    volumes:
      - qdrant_data_4:/qdrant/storage
      - qdrant_snapshots_4:/qdrant/snapshots
    deploy:
      resources:
        limits:
          cpus: '1'

volumes:
  qdrant_data_0:
  qdrant_snapshots_0:
  qdrant_data_1:
  qdrant_snapshots_1:
  qdrant_data_2:
  qdrant_snapshots_2:
  qdrant_data_3:
  qdrant_snapshots_3:
  qdrant_data_4:
  qdrant_snapshots_4:
